language: python
python:
- '3.6'

matric:
  include:
    language: python
    sudo: required
    dist: xenial
    python: "3.7"
cache: pip
install:
- pip install pytest pytest-cov codecov flake8 .
script:
- pytest
- flake8
after_success:
- codecov