language: python
python:
- '3.6'

matrix:
  include:
    - language: python
      sudo: required
      dist: xenial
      python: "3.7"
cache: pip
install:
- pip install codecov flake8 .[dev]
script:
- pytest
- flake8
after_success:
- codecov