language: python
python:
  - "3.6"

cache: pip
env:
  - TOXENV=py36
  - CODECOV_TOKEN="cb408271-e5e1-4c81-9664-2f50ff3edbfc"

install:
  - pip install tox flake8

script:
  - tox -e $TOXENV
  - flake8
